# Generated by Django 3.1.1 on 2020-09-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
